repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  -   id: trailing-whitespace
  -   id: end-of-file-fixer
- repo: https://github.com/psf/black
  rev: 23.12.0
  hooks:
  -   id: black
# - repo: https://github.com/kynan/nbstripout
#   rev: 0.6.1
#   hooks:
#     - id: nbstripout
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.1
  hooks:
    - id: nbqa-black
    #- id: nbqa-isort

ci:
   autofix_prs: true
