name: DGM2lines
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=23.3
  - python=3.9.18
  - conda-lock
  - pip:
      - conda-lock==2.4.2
      - jupyter-book==0.15.1
      - numpy==1.26.1
      - pandas==2.1.3
      - plotly==5.18.0
      - pre-commit==3.5.0
      - xarray==2023.10.1
      - xgcm==0.8.1
