name: DGM2lines
channels:
  - defaults
dependencies:
  - ca-certificates=2023.08.22
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3
  - python=3.9.18
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - accessible-pygments==0.0.4
      - alabaster==0.7.13
      - annotated-types==0.6.0
      - appdirs==1.4.4
      - appnope==0.1.3
      - asttokens==2.4.1
      - attrs==23.1.0
      - babel==2.13.1
      - beautifulsoup4==4.12.2
      - cachecontrol==0.13.1
      - cachy==0.3.0
      - certifi==2023.7.22
      - cfgv==3.4.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - click-default-group==1.2.4
      - clikit==0.6.2
      - cloudpickle==3.0.0
      - comm==0.2.0
      - conda-lock==2.4.2
      - crashtest==0.3.1
      - dask==2023.11.0
      - debugpy==1.8.0
      - decorator==5.1.1
      - distlib==0.3.7
      - docutils==0.18.1
      - ensureconda==1.4.3
      - exceptiongroup==1.1.3
      - executing==2.0.1
      - fastjsonschema==2.18.1
      - filelock==3.13.1
      - fsspec==2023.10.0
      - future==0.18.3
      - gitdb==4.0.11
      - gitpython==3.1.40
      - html5lib==1.1
      - identify==2.5.31
      - idna==3.4
      - imagesize==1.4.1
      - importlib-metadata==6.8.0
      - ipykernel==6.26.0
      - ipython==8.17.2
      - jaraco-classes==3.3.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - jsonschema==4.19.2
      - jsonschema-specifications==2023.7.1
      - jupyter-book==0.15.1
      - jupyter-cache==0.6.1
      - jupyter-client==8.6.0
      - jupyter-core==5.5.0
      - keyring==24.2.0
      - latexcodec==2.0.1
      - linkify-it-py==2.0.2
      - locket==1.0.0
      - markdown-it-py==2.2.0
      - markupsafe==2.1.3
      - matplotlib-inline==0.1.6
      - mdit-py-plugins==0.3.5
      - mdurl==0.1.2
      - more-itertools==10.1.0
      - msgpack==1.0.7
      - myst-nb==0.17.2
      - myst-parser==0.18.1
      - nbclient==0.7.4
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - nodeenv==1.8.0
      - numpy==1.26.1
      - packaging==23.2
      - pandas==2.1.3
      - parso==0.8.3
      - partd==1.4.1
      - pastel==0.2.1
      - pexpect==4.8.0
      - pkginfo==1.9.6
      - platformdirs==3.11.0
      - plotly==5.18.0
      - pre-commit==3.5.0
      - prompt-toolkit==3.0.40
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pybtex==0.24.0
      - pybtex-docutils==1.0.3
      - pydantic==2.4.2
      - pydantic-core==2.10.1
      - pydata-sphinx-theme==0.14.3
      - pygments==2.16.1
      - pylev==1.4.0
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - referencing==0.30.2
      - requests==2.31.0
      - rpds-py==0.12.0
      - ruamel-yaml==0.18.5
      - ruamel-yaml-clib==0.2.8
      - six==1.16.0
      - smmap==5.0.1
      - snowballstemmer==2.2.0
      - soupsieve==2.5
      - sphinx==5.0.2
      - sphinx-book-theme==1.0.1
      - sphinx-comments==0.0.3
      - sphinx-copybutton==0.5.2
      - sphinx-design==0.3.0
      - sphinx-external-toc==0.3.1
      - sphinx-jupyterbook-latex==0.5.2
      - sphinx-multitoc-numbering==0.1.3
      - sphinx-thebe==0.2.1
      - sphinx-togglebutton==0.3.2
      - sphinxcontrib-applehelp==1.0.7
      - sphinxcontrib-bibtex==2.5.0
      - sphinxcontrib-devhelp==1.0.5
      - sphinxcontrib-htmlhelp==2.0.4
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.6
      - sphinxcontrib-serializinghtml==1.1.9
      - sqlalchemy==2.0.23
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tomli==2.0.1
      - tomlkit==0.12.2
      - toolz==0.12.0
      - tornado==6.3.3
      - traitlets==5.13.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - uc-micro-py==1.0.2
      - urllib3==1.26.18
      - virtualenv==20.24.6
      - wcwidth==0.2.9
      - webencodings==0.5.1
      - xarray==2023.10.1
      - xgcm==0.8.1
      - zipp==3.17.0
