name: trigger-book-build
on:
  pull_request:

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: DGM2lines
      artifact_name: book-zip-${{ github.event.number }}
      path_to_notebooks: "book"
      build_command: "jupyter-book build --keep-going ."
      # Other input options are possible, see ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml
