name: trigger-book-build
on:
  pull_request:

jobs:
  build-and-deploy-book:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Get PR number
        run: echo "Your PR is ${PR}"
        env:
          PR: ${{ github.event.pull_request.number }}
      - name: 📦 Cache Conda Packages
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('conda-linux-64.lock') }}
      - name: 🐍 Set up Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          activate-environment: DGM2lines
          environment-file: conda-linux-64.lock
      - name: 👀 Check Conda environment
        shell: bash -l {0}
        run: |
          pip install -r requirements.txt
          conda info
          conda list
      - name: 📦 Cache Notebooks
        uses: actions/cache@v2
        with:
          path: _build/.jupyter_cache
          key: notebook_cache-${{hashFiles('_toc.yml', '_config.yml', 'environment.yml') }}
      - name: 📖 Build the book
        uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
        with:
          environment_name: leap-docs-env
          artifact_name: book-zip-${{ github.event.number }}
          path_to_notebooks: "book"
          build_command: "jupyter-book build -W --keep-going ."
